[build]
  # Ga eerst de 'client' map in om te installeren en te builden
  base    = "client"
  command = "npm install && npm run build"
  publish = "src/build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from    = "/api/*"
  to      = "/.netlify/functions/server/:splat"
  status  = 200
  force   = true

[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
