# netlify.toml
[build]
  command   = "npm run build"
  functions = "netlify/functions"
  publish   = "build"

[[redirects]]
  from    = "/api/*"
  to      = "/.netlify/functions/server/:splat"
  status  = 200
  force   = true

